const BITCOINPRICE = {
    LOAD: 'BITCOIN_PRICE_LOAD',
    LOAD_SUCCESS: 'BITCOIN_PRICE_LOAD_SUCCESS',
    LOAD_FAIL: 'BITCOIN_PRICE_LOAD_FAIL',
};

const BITCOINPRICEHISTORY = {
    LOAD: 'BITCOIN_PRICE_HISTORY_LOAD',
    LOAD_SUCCESS: 'BITCOIN_PRICE_HISTORY_LOAD_SUCCESS',
    LOAD_FAIL: 'BITCOIN_PRICE_HISTORY_LOAD_FAIL',
};

export { BITCOINPRICE, BITCOINPRICEHISTORY };
